Repository gitbrent/PptxGenJS, pull requests merged in 2018-10, with the labels that each got.

#417 fix: Also add the left align property when generating xml paragraph p…
  dist/pptxgen.js
Labels: bug

#409 Improve typescript declaration files
  dist/pptxgen.d.ts
Labels: enhancement

#415 Added better NodeJS checking and better support for Angular
  dist/pptxgen.js
Labels: Angular, enhancement, node.js

#422 BugFix: 0 value plot points ignored on Scatter Chart
  dist/pptxgen.js
Labels: bug
