Repository gitbrent/PptxGenJS, pull requests merged in 2019-01, with the labels that each got.

#466 Pr/420
  dist/pptxgen.js
  examples/pptxgenjs-demo.js
Labels: enhancement-chart

#420 New Feature: Add Data Labels to Scatter Charts
  dist/pptxgen.js
Labels: enhancement-chart

#485 fix ordering of paragraph properties
  dist/pptxgen.js
Labels: bug

#477 BugFix: Hyperlinks causing duplicate relationship ID when other objects on page
  dist/pptxgen.js
Labels: bug

#474 New Chart Option: valAxisCrossesAt
  dist/pptxgen.js
Labels: enhancement-chart

#475 Issue 470 - Formatting issues when using percentages
  dist/pptxgen.js
Labels: enhancement
