Repository gitbrent/PptxGenJS, pull requests merged in 2020-12, with the labels that each got.

#840 Fixes for several rounding mistakes to achieve better precision, accuracy, and usability
  dist/pptxgen.cjs.js
Labels: bug, enhancement

#861 [FEAT] angleRange & arcThicknessRatio properties for shapes
  demos/common/demos.js
  dist/pptxgen.bundle.js
  dist/pptxgen.bundle.js.map
  dist/pptxgen.cjs.js
  dist/pptxgen.es.js
  dist/pptxgen.min.js
  dist/pptxgen.min.js.map
  src/core-interfaces.ts
  src/gen-xml.ts
  src/pptxgen.ts
  types/index.d.ts
Labels: enhancement-shape

#808 Fix data label position for Pie chart
  src/gen-charts.ts
Labels: bug
